version: '3'
services:
  postgres:
      image: postgres
      restart: always
      network_mode: "host"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=mysecretpassword
        - POSTGRES_DB=testing
      volumes:
        - ./psql:/home

